### ISSUE TITLE
Building fails Ubuntu 16.04 (No rule to make target 'libproj.so')

### ISSUE THREAD

**Issue by mad-de** [mad-de/openMVG_gui#1]
waiting for pcl update https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=819608

**Comment by zsustc** [comment]
(1)try to locate libproj.so or its similar style 'libproj.so.*', (2)build a soft link from libproj.so to libproj.so.

**Comment by mad-de** [comment]
Hi. This fork is inactive. Development moved here: https://github.com/open-anatomy/SfM_gui_for_openMVG/
